trigger:
  branches:
    include:
      - main

stages:
  - stage: Build
    jobs:
      - job: BuildApp
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UseNode@1
            inputs:
              version: '18.x'
          - script: yarn install --frozen-lockfile
            displayName: 'Install dependencies'
          - script: yarn build
            displayName: 'Build Vue app'

  - stage: Deploy
    jobs:
      - job: DeployApp
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              echo "$KUBECONFIG" > kubeconfig.yaml
              export KUBECONFIG=kubeconfig.yaml
            displayName: 'Set up Kubernetes context'
          
          - script: |
              helm upgrade --install authflow ./helm/authflow-ui \
                --namespace authflow \
                --set image.repository=your-dockerhub-username/authflow \
                --set image.tag=latest \
                --set service.port=80
            displayName: 'Deploy with Helm'

          - script: |
              helm rollback authflow --namespace authflow
            condition: failed()
            displayName: 'Rollback if failed'
