name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Navigate to authflow Directory
        run: cd authflow

      - name: Install Dependencies
        run: yarn install
        working-directory: ./authflow

      - name: Run Tests
        run: yarn test
        working-directory: ./authflow

      - name: Build App
        run: yarn build
        working-directory: ./authflow

  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Staging Server
        run: echo "Deploying to Staging Server..."
